const { GoogleGenAI } = require("@google/genai")
const { z } = require('zod')
const { zodToJsonSchema } = require("zod-to-json-schema");
// const { resume, selfDescription,jobDescription } = require("../temp");

const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY

});


const interviewReportSchema = z.object({
    matchScore: z.number().describe("The match score in range 0 to 100 indicating how well the candidate's profile matches the job describe"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be asked by the interviewer"),
        intention: z.string().describe("The intention of interviewer behind asking the questions"),
        answer: z.string().describe("How to answer this question , what points to cover,what approach to take etc..")
    })).describe("Technical question that can be asked by the interview along with their intention and how to answer them"),

    behaviouralQuestions: z.array(z.object({
        question: z.string().describe("The behavioural question can be asked by the interviewer"),
        intention: z.string().describe("The intention of interviewer behind asking the questions"),
        answer: z.string().describe("How to answer this question , what points to cover,what approach to take etc..")
    })).describe("Behavioural question that can be asked by the interview along with their intention and how to answer them"),

    skillGapsSchema: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lagging"),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of this skill gap i.e. low, medium, high")
    })).describe("The skill gap that the candidate has along with their severity"),

    preparationPlan: z.array(z.object({
        day: z.number().describe("The day of the preparation plan"),
        tasks: z.array(z.string()).describe("The tasks to be done on this day"),
        focus: z.string().describe("The focus of this day")
    })).describe("The preparation plan per day for the candidate to improve their skills and prepare for the interview"),

}).describe("The interview report generated by the AI based on the job describe and resume text")


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


    const prompt = `You are an AI interview coach. You are given a ${jobDescription}, ${resume} and ${selfDescription}.
    
    You have to generate an interview report for the candidate based on the job describe and resume text. The report should contain the following information:
     1. Match Score: A number in range 0 to 100 indicating how well the candidate's profile matches the job describe.
     2. Technical Questions: A list of technical questions that can be asked by the interviewer along with their intention and how to answer them.
     3. Behavioural Questions: A list of behavioural questions that can be asked by the interviewer along with their intention and how to answer them.
     4. Skill Gap: A list of skills that the candidate is lagging along with their severity i.e. low, medium, high.
     5. Preparation Plan: A preparation plan per day for the candidate to improve their skills and prepare for the interview.
     `


    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema)

        }
    })

    return JSON.parse(response.text)
}
module.exports = generateInterviewReport 